# This is default and very simple configuration file for Yasb. 
# For more information about configuration options, please visit the Wiki https://github.com/amnweb/yasb/wiki
watch_stylesheet: true
watch_config: true
debug: false
update_check: true # Enable automatic update check.
komorebi:
  start_command: "komorebic start --whkd"
  stop_command: "komorebic stop --whkd"
  reload_command: "komorebic stop --whkd && komorebic start --whkd"
bars:
  primary-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: true
    animation:
      enabled: true
      duration: 400
    blur_effect:
      enabled: true
      acrylic: true
      dark_mode: false
      round_corners: false
      round_corners_type: "normal"
      border_color: "system"
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 28
    padding:
      top: 8
      left: 8
      bottom: 0
      right: 8
    widgets:
      left:
        - glazewm_workspaces
      center:
        - clock
      right:
        - systray
        - wifi 
        - volume
        - battery
        - weather
        - notifications

widgets:
  # GlazeWM Workspaces
  # https://github.com/amnweb/yasb/wiki/(Widget)-GlazeWM-Workspaces
  glazewm_workspaces:
    type: "glazewm.workspaces.GlazewmWorkspacesWidget"
    options:
      hide_empty_workspaces: true
      hide_if_offline: true
      enable_scroll_switching: false

  # Clock
  # https://github.com/amnweb/yasb/wiki/(Widget)-Clock
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%I:%M %p}"
      label_alt: "{%A, %d/%m/%Y | %I:%M %p}"
      update_interval: 1000
      tooltip: false
      calendar:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "center"
        direction: "down"
        show_holidays: false
        show_week_numbers: false
      callbacks:
        on_left: "toggle_calendar"
        on_right: "toggle_label"

  # Systray
  # https://github.com/amnweb/yasb/wiki/(Widget)-Systray
  systray:
    type: "yasb.systray.SystrayWidget"
    options:
      class_name: "systray"
      label_collapsed: "◀"
      label_expanded: "▶"
      label_position: "left"
      icon_size: 16
      pin_click_modifier: "alt"
      show_unpinned: false
      show_unpinned_button: true
      show_battery: false
      show_volume: false
      show_network: false

  # Wifi
  # https://github.com/amnweb/yasb/wiki/(Widget)-WiFi
  wifi:
    type: "yasb.wifi.WifiWidget"
    options:
      label: "<span>{wifi_icon}</span>"
      label_alt: "<span>{wifi_icon}</span>{wifi_name}"
      update_interval: 1000
      ethernet_label: "<span>{wifi_icon}</span>"
      ethernet_label_alt: "<span>{wifi_icon}</span>{ip_addr}"
      ethernet_icon: "󰈁"
      get_exact_wifi_strength: true
      wifi_icons: [
        "󰤮 ",  # Icon for 0% strength
        "󰤟 ",  # Icon for 1-24% strength
        "󰤢 ",  # Icon for 25-49% strength
        "󰤥 ",  # Icon for 50-74% strength
        "󰤨 "   # Icon for 75-100% strength
      ]
      menu_config:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "System"
        alignment: "right"
        direction: "down"
        offset_top: 4
        wifi_icons_secured: [
          "󰤡 ",
          "󰤤 ",
          "󰤧 ",
          "󰤪 "
        ]
        wifi_icons_unsecured: [
          "󰤠 ",
          "󰤣 ",
          "󰤦 ",
          "󰤩 "
        ]
      callbacks:
        on_left: "toggle_menu"
        on_right: "toggle_label"

  # Volume
  # https://github.com/amnweb/yasb/wiki/(Widget)-Volume
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span>"
      label_alt: "<span>{icon}</span>{level}"
      tooltip: false
      volume_icons:
        - " "  # Icon for muted
        - " "  # Icon for 0-10% volume
        - " "  # Icon for 11-30% volume
        - " "  # Icon for 31-60% volume
        - " "  # Icon for 61-100% volume
      audio_menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "right"
        direction: "down"
      callbacks:
        on_left: "toggle_volume_menu"
        on_right: "toggle_label"

  # Battery
  # https://github.com/amnweb/yasb/wiki/(Widget)-Battery
  battery:
    type: "yasb.battery.BatteryWidget"
    options:
      label: "<span>{icon}</span>"
      label_alt: "<span>{icon}</span> {percent}% | {time_remaining}"
      update_interval: 1000
      charging_options:
        icon_format: "{charging_icon}"
        blink_charging_icon: false
      status_thresholds:
        critical: 10
        low: 25
        medium: 75
        high: 95
        full: 100
      status_icons:
        icon_charging: "󰂄"
        icon_full: "󰁹"
        icon_high: "󱊣"
        icon_medium: "󱊢"
        icon_low: "󱊡"
        icon_critical: "󱃍"
      callbacks:
        on_left: "do_nothing"
        on_right: "toggle_label"

  # Weather
  # https://github.com/amnweb/yasb/wiki/(Widget)-Weather
  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span>{icon}</span>"
      label_alt: "<span>{icon}</span> {temp}"
      api_key: "89ab7b489811476b9cc34332252210"
      show_alerts: true
      tooltip: false
      hide_decimal: true
      update_interval: 1000
      units: "metric"
      location: "Ho Chi Minh, Viet Nam"
      icons:
        sunnyDay: " "
        clearNight: " "
        cloudyDay: " "
        cloudyNight: " "
        rainyDay: " "
        rainyNight: " "
        snowyIcyDay: " "
        snowyIcyNight: " "
        blizzardDay: "\udb83\udf36"
        blizzardNight: "\udb83\udf36"
        foggyDay: " "
        foggyNight: " "
        thunderstormDay: " "
        thunderstormNight: " "
        default: "\uebaa"
      weather_card:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "right"
        direction: "down"
        time_format: "12h"
        icon_smoothing: true
        offset_top: 4
        icon_size: 64
        show_hourly_forecast: true
        hourly_point_spacing: 88
        hourly_icon_size: 32
        icon_smoothing: true
        temp_line_width: 4
        current_line_color: "#DBBC7F"
        current_line_width: 2
        current_line_style: "dot"
      callbacks:
        on_left: "toggle_card"
        on_right: "toggle_label"

  # Notifications
  # https://github.com/amnweb/yasb/wiki/(Widget)-Notifications
  notifications:
    type: "yasb.notifications.NotificationsWidget"
    options:
      label: "<span> </span>"
      hide_empty: false
      tooltip: false
      callbacks:
        on_left: "toggle_notification"
        on_right: "clear_notifications"
